# MPI wrapper command to compile C++ code
CXX := mpic++

# Location of LSDTopoTools2 
LSDTOPOTOOLS_DIR := lib/LSDTopoTools2

# Location of LibGeoDecomp install base dir
GEODECOMP_DIR := 

# Location of LibGeoDecomp tools dir (provides access to the MPI typemaps generator, only necessary if developing the code)
GEODECOMP_TOOLS_DIR := 

# Location of Boost library install base dir
BOOST_DIR := 

# Location of PnetCDF install base dir
PNETCDF_DIR := 

# Location of the MPI library install base dir
MPI_DIR := 



